version: '3.8'
services:
  
  comet_db:
    image: stariongroup/cdp4-test-database-community-edition:3.4.0
    container_name: comet-db
    shm_size: 2gb
    restart: always
    command: postgres -c max_locks_per_transaction=1024
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    hostname: comet-db
    networks:
      comet:
        aliases:
          - comet-db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - comet-db-data:/var/lib/postgresql/data
      - comet-db-logs:/logs
  
  comet_webservices:
    image: stariongroup/comet-webservices-community-edition:10.0.0-rc1
    container_name: comet-webservices
    shm_size: 512m
    restart: always
    hostname: comet-webservices
    networks:
      comet:
        aliases:
          - comet-webservices
    depends_on:
      - comet_db
    ports:
      - "5000:5000"
    expose:
      - '5000'
    volumes:
      - comet-ws-logs:/app/logs
      - comet-ws-storage:/app/storage
      - comet-ws-uplaod:/app/upload
  
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
    networks:
      - comet
    volumes:
      - 'rabbitmq_data:/data'

networks:
  comet:

volumes:
  comet-db-data:
  comet-db-logs:
  comet-ws-logs:
  comet-ws-storage:
  comet-ws-uplaod:
  rabbitmq_data: