#! /bin/sh
### BEGIN INIT INFO
# Provides: cdp4-webservices
# Description: This file starts and stops the CDP4 Web server
### END INIT INFO

# PATH to CDP4 web service folder without trailing '/'
CDP4_DIR=MIDTIERNANCY

# USER account that runs the CDP4 service
CDP4_USR=CDP4USER

# Get the process id for the running instance of the CDP4 service
getpid() {
  # retrieve the PID by finding the process that runs from the CDP4_DIR, (trailing space is needed)
  PID=`ps -aux -e | grep "mono" | grep "PWD=$CDP4_DIR " | awk '{print $2}'`
  if [ "x$PID" = "x" ]; then
     PID=0
  fi
  return $PID
}

notrunning() {
  echo "CDP4 Web service is not running"
}

startservice() {
   getpid
   if [ $PID -gt 0 ]; then
     echo "CDP4 Web service already running with PID: $PID"
   else
     echo "Starting CDP4 Web service..."
     cd $CDP4_DIR
     su $CDP4_USR -c "mono CDP4WebServer.exe >> output.log 2>&1 &"
   fi
}

stopservice() {
  getpid
  if [ $PID -eq 0 ]; then
     notrunning
  else
    echo "Stopping service ${PID}..."
    su $CDP4_USR -c "kill ${PID} &"
  fi
}

servicestatus() {
  getpid
  if [ $PID -eq 0 ]; then
     notrunning
  else
     echo "CDP4 Web service is running with PID: $PID"
  fi
}

case "$1" in
 start)
   startservice
   ;;
 stop)
   stopservice
   ;;
 restart)
   stopservice
   sleep 1
   startservice
   ;;
 status)
   servicestatus
   ;;
 *)
   echo "Supported commands: start, stop, restart, status"
   ;;
esac